# your domain
domain: guobang.herokuapp.com
port:                 # default 12580

# source list file
source-files:
  # use local file
  # - ./config/source.yaml
  # use web file
  # - https://example.com/config/source.yaml
  # - https://raw.githubusercontent.com/penginman/proxypool/master/config/source.yaml
  - https://raw.githubusercontent.com/penginman/proxypool/master/config/subscribe.yaml
  - https://raw.githubusercontent.com/penginman/proxypool/master/config/tgcapture.yaml
  - https://raw.githubusercontent.com/penginman/proxypool/master/config/webfuzz.yaml

# ======= 可选项，留空使用default值  =======

# postgresql database info
database_url: ""

# speed test
speedtest: true      # default false. Warning: this will consume large network resources.
speedtest-interval:   # default 720 (min)
connection: 1          # default 5. The number of speed test connections simultaneously
timeout:              # default 10 (seconds).
## active proxy speed test
active-interval:      # default 60 (min)
active-frequency:     # default 100 (requests per interval)
active-max-number:    # default 100. If more than this number of active proxies, the extra will be deprecated by speed

# cloudflare api
cf_email: ""
cf_key: ""
